"""Generate src/bench/font.zig: a 6x11 pixel font for bench contact sheets.

Source glyphs are Pillow's built-in legacy bitmap font (a real pixel font,
not a rasterized vector one). Run once; the output is committed.
    python3 tools/bench/gen_font.py > src/bench/font.zig
"""
from PIL import ImageFont, Image, ImageDraw

W, H = 6, 11
f = ImageFont.load_default_imagefont()
print("//! Generated by tools/bench/gen_font.py - 6x11 pixel font, ASCII 32..126.")
print("//! Each glyph is 11 rows; bit 5 is the leftmost pixel.")
print("pub const W = %d;" % W)
print("pub const H = %d;" % H)
print("pub const glyphs = [95][H]u8{")
for c in range(32, 127):
    im = Image.new("1", (W, H), 0)
    ImageDraw.Draw(im).text((0, 0), chr(c), font=f, fill=1)
    rows = []
    for y in range(H):
        v = 0
        for x in range(W):
            if im.getpixel((x, y)):
                v |= 1 << (W - 1 - x)
        rows.append("0x%02x" % v)
    print("    .{ %s }, // %r" % (", ".join(rows), chr(c)))
print("};")
