"""Regenerate docs/20-machine-reference.md from `slab --describe` and the
preset folders. Run after changing a manifest or adding presets:

    PYTHONPATH=tools python3 tools/slabkit/gen_reference.py
"""
import json
import os

from slabkit.machines import ROOT, MACHINES_DIR, machines, presets

OUT = os.path.join(ROOT, "docs", "20-machine-reference.md")


def factory_presets(mid):
    """The factory's presets only: the reference documents what ships,
    not the packs in whoever runs this script's library."""
    base = os.path.join(MACHINES_DIR, mid, "presets")
    names = []
    for dirpath, _, files in os.walk(base):
        names += [os.path.relpath(os.path.join(dirpath, f), base)[: -len(".preset")]
                  for f in files if f.endswith(".preset")]
    return sorted(names, key=lambda n: (n.count("/"), n))


def preset_note(mid, name):
    with open(os.path.join(MACHINES_DIR, mid, "presets", name + ".preset")) as f:
        return json.load(f).get("note", "")


def main():
    db = machines()
    lines = [
        "# 20 — Machine reference",
        "",
        "Generated by `tools/slabkit/gen_reference.py` from `slab --describe` and",
        "`machines/*/presets`. Don't edit by hand. The value columns are what a",
        "project or preset stores (docs/19): real units for knobs, the option",
        "**index** for switches. In slabkit the machine prefix may be dropped",
        "(`cutoff=` for `jn-cutoff`).",
        "",
        "| id | name | kind | voices | prefix |",
        "|---|---|---|---|---|",
    ]
    order = sorted(db.values(), key=lambda m: (m.kind != "instrument", m.id))
    for m in order:
        voices = "—" if m.kind == "effect" else ("mono" if m.mono else m.voices)
        lines.append(f"| [`{m.id}`](#{m.id}) | {m.name} | {m.kind} | {voices} | `{m.prefix or '—'}` |")
    for m in order:
        kind = "stereo insert effect" if m.kind == "effect" else f"instrument, {'mono' if m.mono else f'{m.voices} voices'}"
        lines += ["", f"## {m.id}", "", f"**{m.name}**, {kind}."]
        if m.note_labels:
            lines.append("Drum notes: " + ", ".join(f"{k} = {v}" for k, v in m.note_labels.items()) + ".")
        lines += ["", "| param | section | label | range | default | notes |", "|---|---|---|---|---|---|"]
        for p in m.params.values():
            if p.type == "switch":
                rng = " / ".join(f"{i} {o}" for i, o in enumerate(p.options))
                lines.append(f"| `{p.id}` | {p.module} | {p.label} | {rng} | {p.default:g} | switch |")
            else:
                lines.append(f"| `{p.id}` | {p.module} | {p.label} | {p.min:g} … {p.max:g} | {p.default:g} | "
                             f"{'integer' if p.type == 'int' else p.curve} |")
        ps = factory_presets(m.id)
        if ps:
            lines += ["", "Presets:", ""]
            for name in ps:
                note = preset_note(m.id, name)
                lines.append(f"- `{name}`" + (f" — {note}" if note else ""))
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.relpath(OUT), f"({len(db)} machines)")


if __name__ == "__main__":
    main()
